# Generated by Django 4.2.23 on 2026-05-14 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tool_monitors", "0002_monitordata_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitordata",
            name="string_value",
            field=models.CharField(
                blank=True, default="", help_text="Populated for string-typed columns.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="monitordata",
            name="value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="MonitorColumn",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Column name as it appears in the CSV header.", max_length=255)),
                (
                    "data_type",
                    models.CharField(
                        choices=[("float", "Float"), ("integer", "Integer"), ("string", "String")],
                        default="float",
                        help_text="Expected data type for this column.",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, help_text="Display order on the chart and table.")),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="columns", to="tool_monitors.monitor"
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
                "unique_together": {("monitor", "name")},
            },
        ),
        migrations.AddField(
            model_name="monitordata",
            name="column",
            field=models.ForeignKey(
                blank=True,
                help_text="The column definition this data point belongs to. Null for legacy single-value rows.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_points",
                to="tool_monitors.monitorcolumn",
            ),
        ),
    ]
